### ISSUE TITLE
Error while executing `pip install --editable .`

### ISSUE THREAD

**Issue by kaushal-py** [sipah00/CrickFev#9]
`(scraping) kbstudios@kbstudios:/mnt/Data/Code/kwoc/CrickFev$ pip install --editable .
Obtaining file:///mnt/Data/Code/kwoc/CrickFev
Requirement already satisfied: Click in /home/kbstudios/anaconda3/lib/python3.6/site-packages (from CrickFev==0.1)
Collecting BeautifulSoup (from CrickFev==0.1)
  Using cached BeautifulSoup-3.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-w81v9bsl/BeautifulSoup/setup.py", line 22
        print "Unit tests have failed!"
                                      ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "Unit tests have failed!")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-w81v9bsl/BeautifulSoup/`

This error occured while running
`pip install --editable .`

**Comment by ayush-agr** [comment]
In setup.py install_requires change BeautifulSoup to  BeautifulSoup4. I think there some issue with python and BeautifulSoup versions.

**Comment by SubhrajitPrusty** [comment]
Fixed this in #15  Please take a look.
